# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Historia')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('next_sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=1024)),
                ('data', models.DateTimeField()),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='historia',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Writer'),
        ),
    ]
